### PR TITLE
Avoid use of globals where possible

### LINKED ISSUE #64: React native reference error in 0.5.1
I have been using this library on version 0.4.1 for some time and that works in react-native when running on the simulator with a debugger attached. Running on device results in Reference Error: self is not defined. This should be fixed in issue #53 (With commit f107e7b92d90e4b0287846a49ba3f30d9b9ca648) which is available from version 0.5.0. After upgrading ky to 0.5.0 or 0.5.1 Running on a simulator with a debugger attached or a device results in Reference Error: document is not defined.

I import ky and export an instance as follows:
```
import ky from "ky";
export const api = ky.extend({prefixUrl: BASE_URL});
```

The error shown in the console is as follows:
```
Possible Unhandled Promise Rejection (id: 0):
ReferenceError: document is not defined
ReferenceError: document is not defined
    at new Ky (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:111478:76)
    at Function.ky.(anonymous function) [as post] (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:111772:16)
    at _callee3$ (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:115504:24)
    at tryCatch (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2081:19)
    at Generator.invoke [as _invoke] (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2256:24)
    at Generator.prototype.(anonymous function) [as next] (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2124:23)
    at tryCatch (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2081:19)
    at invoke (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2157:22)
    at blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:2167:15
    at tryCallOne (blob:file:///58581b4b-dc99-4126-b9a9-cb3f918e33f0:6115:14)
```

### PR DESCRIPTION
**Pull request by sholladay**
Fixes #64 

This is similar to PR #69, however I've taken a different approach. Some of my goals include:
 - No regex testing of URLs.
 - Let `fetch()` handle URL resolution where possible.
 - Guard against `ReferenceError`s by not accessing globals when we don't need them.
 - Simplify testing and mocking by treating `global`, `window`, and `self` as not mutually exclusive.

This should make things significantly easier in non-browser environments. In my testing on Node 10+, I was able to remove everything except for `fetch` and `Response` in [test/_require.js](https://github.com/sindresorhus/ky/blob/master/test/_require.js) and the test suite passed.

Previously, Ky would find the global object and then assume everything lived on that object, which makes things cumbersome in non-DOM / no-browser environments. Now, we lookup each global we need in each namespace. So for example, in Node you don't have to implement all of `window` anymore. If you assign a fetch implementation to `window.fetch` but nothing else, Ky will still be able to find `URL` in modern versions of Node where it lives on `global` and you won't have to assign it manually - it will _just work_.

Further, in all environments, globals are conditionally accessed to avoid unnecessary `ReferenceError`s. Ky also no longer relies on the `Headers` class.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
+		return window[property];
 	}
-})();
+
+	return global[property];
+};
+
+const document = getGlobal('document');
+const URL = getGlobal('URL');
+const URLSearchParams = getGlobal('URLSearchParams');
```
Comment (sindresorhus) [inline index.js]: I'm targeting Node.js 10 now, so we can just use `URL` and `URLSearchParams` globals directly in the source. https://github.com/sindresorhus/ky/commit/c5771ee799a9dd8ad8c705262e028f6da19163ee

File: index.js [hunk 2]
```diff
@@ -138,15 +148,21 @@ class Ky {
...
 
-		const url = new _globalThis.URL(this._options.prefixUrl + this._input, document.baseURI);
-		if (typeof searchParams === 'string' || searchParams instanceof _globalThis.URLSearchParams) {
-			url.search = searchParams;
-		} else if (searchParams && Object.values(searchParams).every(param => typeof param === 'number' || typeof param === 'string')) {
-			url.search = new _globalThis.URLSearchParams(searchParams).toString();
-		} else if (searchParams) {
-			throw new Error('The `searchParams` option must be either a string, `URLSearchParams` instance or an object with string and number values');
+		// Avoid using URL() if we can, as it does not support relative URLs
+		// and is yet another global to mock in a non-browser environment.
```
Comment (sindresorhus) [inline index.js]: This comment is confusing as right below it `URL` *is* actually used.

File: test/_require.js [hunk 3]
```diff
@@ -6,6 +6,3 @@ global.Headers = Headers;
 global.Response = Response;
```
Comment (sindresorhus) [inline test/_require.js]: `global.Headers` is no longer needed, I guess.

File: index.js [hunk 4]
```diff
@@ -155,15 +171,18 @@ class Ky {
...
 		if (json) {
-			headers.set('content-type', 'application/json');
+			const headers = this._options.headers &&
+				typeof this._options.headers.entries === 'function' ?
+				objectFromEntries(this._options.headers.entries()) :
+				this._options.headers;
+			this._options.headers = {
+				...headers,
+				'content-type': 'application/json'
+			};
```
Comment (sindresorhus) [inline index.js]: Not a big fan of this. I don't really see the point in adding lots of complications here to save one global. Users needs to polyfill `Response` for Node.js anyway. So adding `Headers` too doesn't change much. The main target is the browser and we should optimize for that.

File: test/_require.js [hunk 5]
```diff
@@ -6,6 +6,3 @@ global.Headers = Headers;
...
 global.URL = URL;
 global.URLSearchParams = URLSearchParams;
```
Comment (sindresorhus) [inline test/_require.js]: Same as https://github.com/sindresorhus/ky/pull/74#discussion_r245502155

**Comment by sindresorhus** [comment]
I like this approach, except for not using `Headers`.

File: index.js (hunk 2 above)
Comment (sholladay) [reply index.js]: True, I agree. Without the comment, though, I feel the purpose is not super obvious. Will try to think of a better way to describe or code it. Suggestions welcome!

File: index.js (hunk 4 above)
Comment (sholladay) [reply index.js]: Yeah, that's fair, I will revert this part. My initial intention was to just do this (without the complicated mess above):

```js
this._options.headers = {
    ...this._options.headers,
    'content-type': 'application/json'
};
```
But then I realized that ky supports custom `Headers` instances and those cannot be spread into an object. It would work with object literals, but not `Headers`.

So, fine, I thought, I'll get its entries and convert it. Seems simple enough. Can't use `Object.entries()` on these `Headers` instances, but `headers.entries()` is a thing. Oh, turns out `headers.entries()` doesn't return a normal entries array, but a `Headers Iterator`. Jeez! Well, at least I can spread that into an array and then use `Object.fromEntries()` to make an object out of it. Nope. `Object.fromEntries()` doesn't have good cross-platform support yet.

This shouldn't be so difficult...  😞

**Comment by sholladay** [comment]
@sindresorhus I think this is ready to go, unless you notice anything else.

Note that I included an unrelated fix for the Travis failures. It was still running Node 8.

**Comment by sindresorhus** [comment]
This is looking great! 👌

@sholladay Would you be interested in joining the project as a maintainer? You have done some really good PRs and you seem interested in the project.

**Comment by sholladay** [comment]
@sindresorhus Yes, would love to join. It's an awesome project. :)

**Comment by sindresorhus** [comment]
Yay. Welcome to the project! 🎉
