### PR TITLE
Fix `BeforeRetryHook` and `NormalizedOptions` TypeScript type definitions

### LINKED ISSUE #288: BeforeRetryHook type definitions
`BeforeRetryHook` has inline type definitions like so:

```ts
export type BeforeRetryHook = (options: {
	request: Request;
	response: Response;
	options: NormalizedOptions;
	error: Error;
	retryCount: number;
}) => void | Promise<void>;
```

Because of that, if I want to declare a `beforeRetry` hook as, for example, a class method, where I'm unable to type it using `BeforeRetryHook` type, I have to type the `options` object manually which is not nice:

```ts
  private async beforeRetry({ error, options }: { error: Error, options: NormalizedOptions }) {
    // ...
  }
```

We should move this inline thing to a stand-alone type, the only problem is to choose a name

UPD: also just noticed `BeforeRetryHook` has return type of `void | Promise<void>`, but it's possible to return symbol `ky.stop` to prevent retrying, but this is now awkward with typescript, because it only wants `void` or `Promise<void>`

### LINKED ISSUE #289: Stand-alone type definitions for NormalizedOptions
Now type definitions for `NormalizedOptions` use `Options` in some fields:

```ts
retry: Options['retry'];
prefixUrl: Options['prefixUrl'];
onDownloadProgress: Options['onDownloadProgress'];
```

For me personally it led to awkward code when trying to use `options.retry.statusCodes`, because TypeScript considers `options.retry` may be `number` or not defined at all, so I have to cast it to `RetryOptions`, and `RetryOptions['statusCode']` is declared optional, so I have to use `!.` which is better than casting, but still awkward. This is not supposed to be like that, because `ky` normalizes all retry options, so in `beforeRetry`, `options.retry` is guaranteed to be `RetryOptions` and `options.retry.statusCodes` is surely `number[]`. There is even a comment in type definitions `// Extended from custom `KyOptions`, but ensured to be set (not optional)`, but typescript doesn't think so

### PR DESCRIPTION
**Pull request by ialexi-bl**
Fixes #289 and fixes #288. The latter can be fixed by #307, but it doesn't include moving arguments that `BeforeRetryHook` receives to a separate object that can later be used to declare `beforeRetry` hooks outside of `ky.create` declaration or actual request.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -11,13 +11,16 @@ export type BeforeRequestHook = (
 	options: NormalizedOptions,
 ) => Request | Response | void | Promise<Request | Response | void>;
 
-export type BeforeRetryHook = (options: {
+export type BeforeRetryOptions = {
 	request: Request;
-	response: Response;
+	response:  Response;
```
Comment (sindresorhus) [inline index.d.ts:16]: Don't do unrelated changes.

**Comment by sindresorhus** [comment]
This needs type tests.

https://github.com/sindresorhus/ky/blob/master/index.test-d.ts

**Comment by sindresorhus** [comment]
Can you rebase from `master`?

**Comment by ialexi-bl** [comment]
Eh, I'm not very familiar with rebases, I hope I didn't messed something up

File: index.d.ts [hunk 2]
```diff
@@ -11,13 +11,16 @@ export type BeforeRequestHook = (
 	options: NormalizedOptions,
 ) => Request | Response | void | Promise<Request | Response | void>;
 
-export type BeforeRetryHook = (options: {
+export type BeforeRetryOptions = {
```
Comment (sindresorhus) [inline index.d.ts:14]: I don't think "options" is the correct word here.

File: index.test-d.ts [hunk 3]
```diff
@@ -48,7 +48,9 @@ ky(url, {
 			}
 		],
 		beforeRetry: [
-			({request, response, options, error, retryCount}) => {
+			(beforeRetryOptions) => {
+				const { request, response, options, error, retryCount } = beforeRetryOptions
```
Comment (sindresorhus) [inline index.test-d.ts:52]:
```suggestion
				const {request, response, options, error, retryCount} = beforeRetryOptions
```

File: index.d.ts (hunk 2 above)
Comment (ialexi-bl) [reply index.d.ts:14]: What one then? Maybe Params?

Comment (sindresorhus) [reply index.d.ts:14]: It's better to present solutions than asking questions. Try to think of some good names. I don't think `Params` is a good name. We try not to use abbreviations here.

Comment (ialexi-bl) [reply index.d.ts:14]: Well, I can't think of a better name than "parameters". The properties of this object don't have anything in common so that there could be a sensible name for them as a whole, it's there just to reduce amount of arguments for `beforeRetry`. Params seems like a very common abbreviation, but it could be `BeforeRetryParameters`. If not this word, I don't know what one tbh

Comment (sholladay) [reply index.d.ts:14]: I would name it `BeforeRetryState`.

If not `State`, then some other ideas...
 - `Context`
 - `Record`
 - `Variables` (or `Vars`)
 - `Properties` (or `Props`)
 - `Arguments` (or `Args`)

Comment (sindresorhus) [reply index.d.ts:14]: > Well, I can't think of a better name tha "parameters".

Naming is indeed hard, but I don't think you tried your best here. All I asked was to come up with some alternatives.

Comment (sindresorhus) [reply index.d.ts:14]: I prefer `Context`, but `State` would work too.

Comment (ialexi-bl) [reply index.d.ts:14]: > Naming is indeed hard, but I don't think you tried your best here.

Well, sorry for not doing my best for someone else's library. I'll change it to `State`

**Comment by sindresorhus** [comment]
Thanks for the PR :)
