### PR TITLE
Fix Error types

### LINKED ISSUE #112: HTTPError type incorrect
When trying to create a `new HTTPError` using a response, Typescript says that `HTTPError` only accepts a message as a `string | undefined`. The source shows that it should accept a `Response` object.

### PR DESCRIPTION
**Pull request by stramel**
Fixes #112 

Adds `constructor` definitions for both `HTTPError` and `TimeoutError`

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -122,13 +122,16 @@ export interface ResponsePromise extends Promise<Response> {
...
+	constructor(response: Response);
 	response: Response;
 }
 
 /**
  * The error thrown when the request times out.
  */
-export class TimeoutError extends Error {}
+export class TimeoutError extends Error {
+	constructor();
```
Comment (sholladay) [inline index.d.ts]: Can TypeScript not figure this out on its own? Seems silly.

Comment (stramel) [reply index.d.ts]: It was using the Error constructor which accepts a message.

Comment (sholladay) [reply index.d.ts]: Yeah, I get the intention of the type definition. I'm just a bit surprised that TypeScript can't figure out that this function doesn't accept any arguments.

Comment (stramel) [reply index.d.ts]: I believe that Typescript would be smart enough to infer the proper constructor if our implementation was written in Typescript.

Comment (sholladay) [reply index.d.ts]: Yeah, perhaps. Seems like a good feature request, in any case.
