### PR TITLE
Fix `afterResponse` hook & retry not being called

### LINKED ISSUE #94: afterResponse hooks not fired if await ky directly
As discussed in Pr #93:
`afterResponse` hooks are not executed for the following code:

```js
const response = await ky.get('https://example.com', {
    hooks: {
        afterResponse: [
             response => {
                 // This won't get called
             }
         ]
     }
});

const data = await response.json();
```

I know this is not how `ky` is supposed to be used, but it's easy to fall into this and see that everything is working, except the hooks.

### LINKED ISSUE #96: Error not thrown without the json method
Hi,

I was just trying to catch errors in the front-end of my react/redux app when I spotted a really odd behavior.

- When doing a DELETE request on my API without ".json()" appended to my response, http errors are not thrown, even with throwHttpErrors forced true in the options.

```js
try {
    await api.delete(`roles/${id}`);
    dispatch(actions.deleteRole(id));
  } catch (error) {
    dispatch({
      type: types.DELETE_ROLE_ERROR,
      payload: {
        error,
      },
    });
  }
```

- When doing the same DELETE request with ".json()" appended to the response, errors are thrown but the request is fired twice so the second one always returns a 404.

```js
try {
    await api.delete(`roles/${id}`).json();
    dispatch(actions.deleteRole(id));
  } catch (error) {
    dispatch({
      type: types.DELETE_ROLE_ERROR,
      payload: {
        error,
      },
    });
  }
```

Any idea why this would happen?

### PR DESCRIPTION
**Pull request by 7Pass**
Fixes #94
Fixes #96

~~`ky` will no longer return a promise directly. It now returns an object with Body methods, plus a `raw` method to retrieve a cloned `Response` directly, useful when there's a need to simply check status code.~~

Note from @szmarczak: I've edited this PR so it should work properly now.

#### TODO:

 - [x] Tests

### CODE REVIEW

**Comment by 7Pass** [comment]
This fixes bug #94

**Comment by 7Pass** [comment]
Then we can return the `raw()` call and attach the body methods to that promise instead. I'm not sure the memory affect because the Response will be cloned twice: once for the returned object, then another time for the body object.

**Comment by szmarczak** [comment]
I agree with @sholladay. The idea of `getResponse` function seems to be nice. I'll try to fix this PR.

**Comment by szmarczak** [comment]
There's another bug: it will make another request when using method shortcuts...

File: index.js [hunk 1]
```diff
@@ -181,34 +181,32 @@ class Ky {
...
+			}
 
-					if (modifiedResponse instanceof Response) {
-						response = modifiedResponse;
-					}
-				}
+			return response;
+		};
 
-				if (!response.ok && (isRetriableMethod || this._throwHttpErrors)) {
```
Comment (szmarczak) [inline index.js]: I've removed `isRetriableMethod` check here, I don't think it's needed here...

**Comment by szmarczak** [comment]
TODO: tests

File: index.js [hunk 2]
```diff
@@ -181,34 +181,32 @@ class Ky {
...
-					throw new HTTPError(response);
-				}
+		const isRetriableMethod = retryMethods.has(this._options.method.toLowerCase());
+		this._response = isRetriableMethod ? this._retry(fn) : fn();
```
Comment (sholladay) [inline index.js]: Unrelated to this PR, but it's been bothering me that `this._response` is saved on the instance despite only being used in the scope of the constructor. I'm pretty sure we can just do `const result =` instead of `this._response =`.

**Comment by sholladay** [comment]
Awesome! This is exactly what I was hoping for. 👏 

I don't see any obvious problems. I will play around with this in my app in the next day or two.

File: index.js (hunk 2 above)
Comment (szmarczak) [reply index.js]: Sure, I saw this too but maybe it was done like so for some reason.

@sindresorhus What do you think?

Comment (sindresorhus) [reply index.js]: 👍👍

**Comment by sindresorhus** [comment]
> In my opinion, we should remain as close to the fetch API as we reasonably can, so that Ky is intuitive and familiar. I'm 👎 on this particular design. I'm pretty sure we can fix the bug without changing our return type.

👍

File: index.js (hunk 2 above)
Comment (szmarczak) [reply index.js]: `const result` or `this._response`?

Comment (sindresorhus) [reply index.js]: `const result`

**Comment by szmarczak** [comment]
I'll write the tests tomorrow
